/* LOG DE LOGINS AL SISTEMA */
CREATE TABLE com_nodoLogIngresoSinges(
	id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	idNodo BIGINT NOT NULL,
	fechaIngreso DATETIME NOT NULL DEFAULT(GETDATE()),
	ipIngreso VARCHAR(20) NOT NULL,
	eliminado BIT NOT NULL DEFAULT(1)
);

ALTER TABLE com_nodoLogIngresoSinges ADD FOREIGN KEY (idNodo) REFERENCES com_nodo(id);

/* LOG CAMBIO CONTRASEÑAS DE LOS NODOS */
CREATE TABLE com_nodoLogContrasenas(
	id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	idNodo BIGINT NOT NULL,
	fechaCambio DATETIME NOT NULL DEFAULT(GETDATE()),
	contrasenaAntigua VARCHAR(100) NOT NULL,
	eliminado BIT NOT NULL DEFAULT(1)
);

ALTER TABLE com_nodoLogContrasenas ADD FOREIGN KEY (idNodo) REFERENCES com_nodo(id);

/* LOG CAMBIOS DEL SALARIO DE LOS NODOS */
CREATE TABLE com_nodoLogSalario(
	id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	idNodo BIGINT NOT NULL,
	valor INT NOT NULL,
	fecha DATE NOT NULL,
	eliminado BIT NOT NULL DEFAULT(1)
);

ALTER TABLE com_nodoLogSalario ADD FOREIGN KEY (idNodo) REFERENCES com_nodo(id);