INSERT INTO portal_aplicacionCodigos VALUES ('spl-selectActRegisters', 'Seleccionar registros de activación');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-selectActRegisters' WHERE ruta = 'Principal/seleccionarPlanillasIniciales';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-printDocuments', 'Registros de activación listos para imprimir');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-printDocuments' WHERE ruta = 'Principal/generarDocumentoImpresion';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-sendClaroDocuments', 'Recibir y enviar documentos a Claro');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-sendClaroDocuments' WHERE ruta = 'Principal/enviarDocumentosParaClaro';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-getActRegisters', 'Recibir registros de activación en sucursal');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-getActRegisters' WHERE ruta = 'Principal/recibirPlanilla';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-createActRegSolution', 'Crear solución de registro de activación');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-createActRegSolution' WHERE ruta = 'Principal/crearPlanillaSolucion';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-deleteRegSend', 'Borrar envío de registro de activación');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-deleteRegSend' WHERE ruta = 'Principal/cargarBorrarPlanillaEnvio';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-searchActRegister', 'Buscar registro de activación');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-searchActRegister' WHERE ruta = 'Principal/buscarPlanilla';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-createAuthNumber', 'Crear número de autorización');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-createAuthNumber' WHERE ruta = 'Principal/cargarCrearAutorizacion';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-createActRegister', 'Crear registro de activación - cambio de servicio');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-createActRegister' WHERE ruta = 'Principal/cargarPlanillaCambioServicio';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-changeActRegState', 'Cambio de estado registro de activación');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-changeActRegState' WHERE ruta = 'Principal/cargarFormulario/cambioEstado';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-changeActRegNum', 'Cambio número registro de activación');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-changeActRegNum' WHERE ruta = 'Principal/cargarFormulario/cambioNumPlani';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-getActRegClaro', 'Recibir registros de activación de Claro');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-getActRegClaro' WHERE ruta = 'Principal/recibirPlanillaDeClaro';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-authRegAct', 'Autorizar registro de activación día');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-authRegAct' WHERE ruta = 'Principal/autorizacionPlanilla';
INSERT INTO portal_aplicacionCodigos VALUES ('spl-cancelRegAct', 'Anulación registro de activación');
UPDATE portal_menuAplicacion SET codPermiso = 'spl-cancelRegAct' WHERE ruta = 'Principal/cargarAnularPlanilla';