INSERT INTO portal_aplicacionCodigos VALUES ('ipo-adminEmailSent', 'Funcionalidad de correos enviados en IPortal/adminSinges');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-adminRedirect', 'Redireccionamiento por rol');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-adminSuc', 'Administrar las sucursales aliadas');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-appCreate', 'Crear una nueva aplicación en Singes');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-appDelete', 'Eliminar una aplicación de Singes');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-appModify', 'Modificar una aplicación de Singes');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-appSeach', 'Buscar una aplicación de Singes');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-configMenu', 'Código de acceso para configurar el menú de navegación');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultPlan', 'Consultar los planes en iPortal/adminSinges/precios/planes');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultPlan0points', 'Consultar plan sin puntos en iPortal/adminSinges/precios/planes');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consulTypeMatrix', 'Consultar tipos de matriz');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createPlan', 'Crear un plan en iPortal/adminSinges/precios/planes');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createPollBody', 'Crear el cuerpo de encuesta');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createPollGroup', 'Crear grupos de encuestas');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createTypeMatrix', 'Crear tipo de matriz');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-gifts', 'Consultar los obsequios');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyPlan', 'Editar los plantes en iPortal/adminSinges/precios/planes');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyPollGroup', 'Modificar los grupos de encuestas');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyTypeMatrix', 'Modificar tipos de matriz');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-seeSingesHow	Código de acceso para funcionalidad de VerSingesComo en Iportal/Menú');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-updateMatrixPlan	Actualizar matriz de equipo (plan)');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-updateProm', 'Actualizar promociones');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-updateCircFull', 'Actualizar circulares full precio');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-updateCircKit', 'Actualizar circulares kit');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-updateCircPost', 'Actualizar circulares postpago');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-updateCircShare', 'Actualizar circulares cuotas');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-compPostvsFree', 'Comparación de precios equipos post vs libre CAD');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-itemWithoutPrice', 'Items sin precios');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultRangesCFM', 'Consultar rangos de descuento cfm');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createRangesCFM', 'Crear rangos de descuento cfm');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-editRangesCFM', 'Editar rangos de descuento cfm');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-deleteRangesCFM', 'Eliminar rangos de descuento cfm');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultCircCFM', 'Items de costo fijo mensual (cfm)');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createBanners', 'Creación de banners');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyBanners', 'Editar - banners creados actualmente');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-adminPic&Plac', 'Administración del pico y placa claro');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createPointsRef', 'Crear puntos por referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultPointsRef', 'Consultar caracteristicas de una referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyPointsRef', 'Modificar caracteristicas de una referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-buttonFact', 'Permisos botón facturar ayuda ventas');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-assignListPrices', 'Asignación listas de precios');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createTypeFeature', 'Crear tipo caracteristica');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultTypeFeature', 'Consultar tipo de caracteristicas');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyTypeFeature', 'Modificar tipo de caracteristica');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createGroupFeature', 'Crear grupo caracteristica');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultGroupFeature', 'Consultar grupo de caracteristicas');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyGroupFeature', 'Modificar grupo de caracteristicas');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createFeature', 'Crear caracteristica');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultFeature', 'Consultar caracteristica');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyFeature', 'Modificar caracteristicas');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultPlanFeature', 'Consultar caracteristicas de un plan');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyPlanFeature', 'Modificar caracteristicas de un plan');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultTeamFeature', 'Consultar Caracteristicas de una Referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyTeamFeature', 'Modificar Caracteristicas de una Referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createImgRef', 'Crear imanges referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-assignPermits', 'Asignar permisos a los paneles de singes');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultTypePl', 'Consultar tipo de planilla');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createTypePl', 'Crear tipo de planilla');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyTypePl', 'Modificar tipo de planilla');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createStates302', 'Crear estados devolución 302');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultStates302', 'Consultar estados devolución 302');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-editStates302', 'Editar estados devolución 302');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-deleteStates302', 'Eliminar estados devolución 302');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-authByRol&Node', 'Autorización por rol y nodo');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createSucZone', 'Crear sucursal zona');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultSucZone', 'Consultar sucursal por zona');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifySucZone', 'Modificar sucursal por zona');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-loadIncomes', 'Ingreso de recaudos, accesorios y pasatiempos');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-verifyCloseSuc', 'Verificación cierre sucursales');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-loadCloseDateGen', 'Fecha de cierre general');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createBlkState', 'Crear estado bloqueo');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultBlkState', 'Consultar estado bloqueo');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyBlkState', 'Modificar estado bloqueo');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createGlobalVar', 'Crear variable global');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultGlobalVar', 'Consultar variables globales');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyGlobalVar', 'Modificar variables globales');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-createBiometric', 'Relacionar lector biometríco');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-consultBiometric', 'Consultar lector biometríco');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-modifyBiometric', 'Modificar lector biometríco');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-adminFacSerial', 'Usuarios con acceso a facturar por serial');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-incMasterPoints', 'Inconsistencias maestro puntos');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-landingPRelTeam', 'Relación de equipos en los landing page');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-landingPEditTeam', 'Edición de equipos en los landing page');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-deleteCloseOp', 'Eliminar cierre de operaciones');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-loadCircularTech', 'Carga de circular tecnología');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-cleanServers', 'Limpiar servidores');
INSERT INTO portal_aplicacionCodigos VALUES ('ipo-activateLicenses', 'Activación licencias de Microsoft');

UPDATE portal_menuAplicacion SET codPermiso = 'ipo-appCreate' WHERE id = 4;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-appSeach' WHERE id = 5;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-appModify' WHERE id = 6;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-appDelete' WHERE id = 7;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-configMenu' WHERE id = 8;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-updateMatrixPlan' WHERE id = 188;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createPlan' WHERE id = 296;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultPlan' WHERE id = 297;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyPlan' WHERE id = 298;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-updateProm' WHERE id = 325;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyTypeMatrix' WHERE id = 303;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyPollGroup' WHERE id = 495;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createPollBody' WHERE id = 497;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-updateCircFull' WHERE id = 585;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createTypeMatrix' WHERE id = 301;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consulTypeMatrix' WHERE id = 302;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-adminRedirect' WHERE id = 768;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-adminEmailSent' WHERE id = 796;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-adminSuc' WHERE ruta = 'adminSucursal';
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createPollGroup' WHERE id = 494;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-seeSingesHow' WHERE id = 703;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultPlan0points' WHERE id = 708;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-gifts' WHERE id = 761;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-updateCircKit' WHERE id = 190;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-updateCircPost' WHERE id = 191;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-updateCircShare' WHERE id = 434;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-compPostvsFree' WHERE id = 681;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-itemWithoutPrice' WHERE id = 707;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultRangesCFM' WHERE id = 738;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createRangesCFM' WHERE id = 739;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-editRangesCFM' WHERE id = 740;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-deleteRangesCFM' WHERE id = 741;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultCircCFM' WHERE id = 742;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createBanners' WHERE ruta = 'adminBanners/bannersController/crearNuevoBanner/4';
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyBanners' WHERE ruta = 'adminBanners/bannersController/editarBanner/4';
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-adminPic&Plac' WHERE id = 88;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createPointsRef' WHERE ruta = 'Inicio/crearPuntosReferencia';
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultPointsRef' WHERE ruta = 'Inicio/consultarPuntosReferencia';
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyPointsRef' WHERE ruta = 'Inicio/modificarPuntosReferencia';
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-buttonFact' WHERE id = 186;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-assignListPrices' WHERE id = 206;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createTypeFeature' WHERE id = 374;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultTypeFeature' WHERE id = 375;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyTypeFeature' WHERE id = 376;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createGroupFeature' WHERE id = 378;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultGroupFeature' WHERE id = 379;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyGroupFeature' WHERE id = 380;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createFeature' WHERE id = 382;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultFeature' WHERE id = 383;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyFeature' WHERE id = 384;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultPlanFeature' WHERE id = 390;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyPlanFeature' WHERE id = 391;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultTeamFeature' WHERE id = 387;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyTeamFeature' WHERE id = 388;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createImgRef' WHERE id = 745;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-assignPermits' WHERE id = 294;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultTypePl' WHERE id = 399;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createTypePl' WHERE id = 400;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyTypePl' WHERE id = 401;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createStates302' WHERE id = 732;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultStates302' WHERE id = 733;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-editStates302' WHERE id = 734;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-deleteStates302' WHERE id = 735;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-authByRol&Node' WHERE id = 882;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createSucZone' WHERE id = 447;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultSucZone' WHERE id = 448;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifySucZone' WHERE id = 449;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-loadIncomes' WHERE id = 392;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-verifyCloseSuc' WHERE id = 333;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-loadCloseDateGen' WHERE id = 334;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createBlkState' WHERE id = 329;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultBlkState' WHERE id = 330;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyBlkState' WHERE id = 331;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createGlobalVar' WHERE id = 525;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultGlobalVar' WHERE id = 526;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyGlobalVar' WHERE id = 527;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-createBiometric' WHERE id = 654;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-consultBiometric' WHERE id = 655;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-modifyBiometric' WHERE ruta = 'Inicio/modificarBiometrico';
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-adminFacSerial' WHERE id = 710;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-incMasterPoints' WHERE id = 711;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-landingPRelTeam' WHERE id = 579;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-landingPEditTeam' WHERE id = 580;
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-deleteCloseOp' WHERE ruta = 'eliminarCierreOperacion';
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-loadCircularTech' WHERE id = 'circular';
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-cleanServers' WHERE ruta = 'limpiar/servidores';
UPDATE portal_menuAplicacion SET codPermiso = 'ipo-activateLicenses' WHERE id = 905;