INSERT INTO portal_aplicacionCodigos VALUES ('rve-foliosReport', 'Reportes de folios');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-foliosReport' WHERE ruta = 'Principal/puntosFolios';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-salesReportXbrands', 'Reporte de ventas por marcas');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-salesReportXbrands' WHERE ruta = 'principal/ventasPorMarca';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-advisorSalesReport', 'Reporte de ventas asesor');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-advisorSalesReport' WHERE ruta = 'Principal/ventasAsesor/asesor';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-adminSalesReport', 'Reporte de ventas asesor - administrador');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-adminSalesReport' WHERE ruta = 'Principal/ventasAsesor/admin';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-directorSalesReport', 'Reporte de ventas asesor - director');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-directorSalesReport' WHERE ruta = 'Principal/ventasAsesor/director';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-migrationsReport', 'Reporte de migraciones');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-migrationsReport' WHERE ruta = 'Principal/reporteMigraciones';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-comparePoints', 'Comparación de puntos');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-comparePoints' WHERE ruta = 'Principal/verificarCuerpoVsMaestro';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-postPlanesReport', 'Reporte de planes postpago');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-postPlanesReport' WHERE ruta = 'Principal/reportePlanesPostpago';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-accsSales', 'Ventas de accesorios');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-accsSales' WHERE ruta = 'principal/ventasPorAccesorios';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-createBudget', 'Crear presupuesto Singular');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-createBudget' WHERE ruta = 'Principal/crearPresupuesto';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-reportDirectorPoints', 'Reportes de puntos directores');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-reportDirectorPoints' WHERE ruta = 'principal/puntosdirectores';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-averageAdvisorSales', 'Promedio ventas asesor');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-averageAdvisorSales' WHERE ruta = 'Principal/ventasAsesorPuntos';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-compliceThresholds', 'Cumplimiento de umbrales');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-compliceThresholds' WHERE ruta = 'Principal/reporteCumplimientoUmbrales';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-noReturnSalesReport', 'Reporte de ventas sucursal y asesor');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-noReturnSalesReport' WHERE ruta = 'Principal/reporteVentasSinDevoluciones';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-pointsReport', 'Reportes de puntos');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-pointsReport' WHERE ruta = 'principal/puntosVentas';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-sucursalSalesReport', 'Reporte de ventas asesor - Sucursal');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-sucursalSalesReport' WHERE ruta = 'Principal/ventasAsesor/sucursal';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-suc&advSalesReport', 'Reporte de ventas por sucursal y asesor');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-suc&advSalesReport' WHERE ruta = 'Principal/reporteVentasSucursal';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-modifyBudget', 'Modificar presupuesto singular');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-modifyBudget' WHERE ruta = 'modificarPresupuesto';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-weeklyCompAdvs', 'Cumplimiento semanal de asesores');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-weeklyCompAdvs' WHERE ruta = 'Principal/reporteSucursalCumpleSemana';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-pac&refSalesReport', 'Reporte venta de recargas y paquetes');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-pac&refSalesReport' WHERE ruta = 'Principal/ventaRecargasKinacu';
INSERT INTO portal_aplicacionCodigos VALUES ('rve-portalsReports', 'Reporte de portaciones');
UPDATE portal_menuAplicacion SET codPermiso = 'rve-portalsReports' WHERE ruta = 'Principal/reportePortaciones';