INSERT INTO portal_aplicacionCodigos VALUES ('inv-createItemDTH', 'Crear item (dth)');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultItemDTH', 'Consultar item (dth)');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyItemDTH', 'Modificar item (dth)');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-assignGoods', 'Asignar mercancias');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-unassignInv', 'Desasignar inventario');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-ungroupInv', 'Desagrupar inventario');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultRefDTH', 'Consultar referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyRefDTH', 'Modificar referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-deleteRefDTH', 'Eliminar referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createRefDTH', 'Crear referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-profileRefPlan', 'Perfilamiento referencia con planes');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-profileRefSuc', 'Perfilamiento sucursal con perfil referencia');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createGroupTaxes', 'Crear impuesto - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultGroupTaxes', 'Consultar impuestos - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyGroupTaxes', 'Modificar impuestos - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-deleteGroupTaxes', 'Eliminar impuestos - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createTypeMove', 'Crear tipo de movimiento - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultTypeMove', 'Consultar tipo de movimiento - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyTypeMove', 'Modificar tipo de movimiento - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-deleteTypeMove', 'Eliminar tipo de movimiento - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createProductGroup', 'Crear producto - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultProductGroup', 'Consultar productos - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyProductGroup', 'Modificar productos - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-deleteProductGroup', 'Eliminar productos - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createTypeInv', 'Crear tipo de inventario - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultTypeInv', 'Consultar tipo de inventario - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyTypeInv', 'Modificar tipo de inventario - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createTypeGroup', 'Crear tipo de grupo');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultTypeGroup', 'Consultar tipo de grupo');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyTypeGroup', 'Modificar tipo de grupo');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createItemAcc', 'Crear item de accesorios');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createItemBrand', 'Crear marca de items');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultItemBrand', 'Consultar marca de items');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyItemBrand', 'Modificar marca de items');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-deleteItemBrand', 'Eliminar marca de items');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createItemColor', 'Crear color de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultItemColor', 'Consultar color de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyItemColor', 'Modificar color de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-deleteItemColor', 'Eliminar color de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createItemState', 'Crear estado de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultItemState', 'Consultar estado de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyItemState', 'Modificar estado de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createItemCat', 'Crear cátegoria items');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultItemCat', 'Consultar cátegoria items');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyItemCat', 'Modificar cátegoria items');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createRefItem', 'Crear referencia de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultRefItem', 'Consultar referencia de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyRefItem', 'Modificar referencia de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-deleteRefItem', 'Eliminar referencia de item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultCellar', 'Consultar bodega');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createCellar', 'Crear bodega');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyCellar', 'Modificar bodega');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createConsLot', 'Crear consecutivo lote');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyConsLot', 'Modificar consecutivo lota');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createConsXSuc', 'Crear consecutivo por sucursal');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultConsXSuc', 'Consultar consecutivos por sucursal');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyConsXSuc', 'Modificar consecutivos por sucursal');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createSerialState', 'Crear estado serial');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultSerialState', 'Consultar estados serial');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifySerialState', 'Modificar estado serial');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-deleteSerialState', 'Eliminar estado serial');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createConcept', 'Crear concepto');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultConcept', 'Consultar concepto');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyConcept', 'Modificar concepto');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createTypeConcept', 'Crear tipo de concepto');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultTypeConcept', 'Consultar tipos de conceptos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyTypeConcept', 'Modificar tipos de conceptos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createPricesList', 'Crear lista de precio');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyPricesList', 'Modificar lista precio');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultPricesList', 'Consultar lista precio');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createGroup', 'Crear grupo');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultGroup', 'Consultar grupo');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyGroup', 'Modificar grupo');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-deleteGroup', 'Eliminar grupo');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createItem', 'Crear item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultItem', 'Consultar item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyItem', 'Modificar item');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-compInvs', 'Comparador de inventarios');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultInvGroups', 'Consultar inventario grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultInvGrpUnserial', 'Consultar inventario grupos - no serializados');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultInvDoc', 'Consultar inventario documento - grupos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultIvnAva', 'Consultar inventario disponible');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultInvNational', 'Consultar inventario disponible nacional');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultInvPost30', 'Consultar equipos con más de 30 días en inventario');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultGenStock', 'Consultar stock general');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consulTransfers', 'Consultar traslados');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultSellsKinacu', 'Consultar ventas Kinacu');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-changeSerialStates', 'Cambiar estados seriales');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultResSerial', 'Consultar serial Reservado');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultSerial', 'Consultar serial');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultSerialStates', 'Consultar estado serial');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultLotSuc', 'Consultar lotes por sucursal');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultLot', 'Consultar lotes');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultLotSerialsAv', 'Consultar lotes disponibles');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultRefAccesory', 'Reporte referencia sin homólogo');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-accesoryRelEquip', 'Accesorios relación a equipos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultEquiPrice', 'Precio de accesorios');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultEquipAccs', 'Consultar accesorios de equipo');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultHomoEquip', 'Consultar homologación de equipos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createHomo', 'Crear nuevo homólogo');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultHomoRef', 'Consultar homólogos - referencias');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-relAccsHomo', 'Relación accesorios a homólogos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-relHomoAccs', 'Relación homólog con accesorios');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultHomoItems', 'Consultar homologación de items');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultAccsStock', 'Consultar stock de accesorios');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultItemInv', 'Consultar item de inventario');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultGroupInv', 'Consltar grupo de inventario');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-returnBillClaro', 'Doc021 - Devolución factura claro');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createDoc122', 'Creación de un documento 122');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultDoc122', 'Consultar documento 122');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createDoc121', 'Crear un documento 121');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createBundle', 'Crear un bundle');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createConsPre', 'Crear consecutivos precintos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultConsPre', 'Consultar consecutivos precintos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-assignConsPre', 'Asignar consecutivos precintos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultConsAssigned', 'Consultar consecutivos precintos asignados');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-editConsAssigned', 'Editar consecutivos precintos asignados');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createSeals', 'Crear precintos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultSeals', 'Consultar precintos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifySeals', 'Modificar precintos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc112', 'Cargar documento 112');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc005', 'Cargar documento 005');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc006', 'Cargar documento 006');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc110', 'Cargar documento 110');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc111', 'Cargar documento 111');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc301', 'Cargar documento 301');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc000', 'Cargar documento 000');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc003', 'Cargar documento 003');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc013', 'Cargar documento 013');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc004', 'Cargar documento 004');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc210', 'Cargar documento 210');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc211', 'Cargar documento 211');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc011', 'Cargar documento 011');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc011-1', 'Cargar documento 011-1');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc011-2-1', 'Cargar documento previo 011-2-1');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc007', 'Cargar documento 007');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadDoc007-1', 'Cargar documento 007-1');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-modifyPurchOrder', 'Modificar orden de compra');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-consultPurchOrder', 'Consultar orden de compra');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-createReport', 'Crear reporte');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadFileCat', 'Carga archivo categorías');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadFileRef', 'Carga archivo referencias');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadFileItem', 'Carga archivo items');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadFileSerial', 'Carga archivo serial');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadFileRelSuc', 'Carga archivo relación sucursal');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadFileSucListPrices', 'Carga archivo relación sucursal lista precios');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadFileHomoEquip', 'Carga archivo homologación de equipos');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadListPrices', 'Carga archivo listado de precios');
INSERT INTO portal_aplicacionCodigos VALUES ('inv-loadListCodes', 'Carga archivo listado de códigos productos');

UPDATE portal_menuAplicacion SET codPermiso = 'inv-createItemDTH' WHERE id = 689;
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultItemDTH' WHERE ruta = 'Principal/consultarItem/dth';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyItemDTH' WHERE ruta = 'Principal/modificarItem/dth';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-assignGoods' WHERE ruta = 'Principal/asignacion';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-unassignInv' WHERE ruta = 'Dth/desasignarInventarioInstalador';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-ungroupInv' WHERE ruta = 'Dth/desagrupar';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultRefDTH' WHERE ruta = 'Principal/consultarReferencia/dth';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyRefDTH' WHERE ruta = 'Principal/modificarReferencia/dth';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-deleteRefDTH' WHERE ruta = 'Principal/eliminarReferencia/dth';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createRefDTH' WHERE ruta = 'Principal/crearReferencia/dth';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-profileRefPlan' WHERE ruta = 'perfil/referenciaPlan';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-profileRefSuc' WHERE ruta = 'perfil/sucursalReferencia';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createGroupTaxes' WHERE ruta = 'Principal/crearImpuesto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultGroupTaxes' WHERE ruta = 'Principal/consultarImpuestos';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyGroupTaxes' WHERE ruta = 'Principal/modificarImpuestos';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-deleteGroupTaxes' WHERE ruta = 'Principal/eliminarImpuestos';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createTypeMove' WHERE ruta = 'Principal/crearTipoMovimiento'
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultTypeMove' WHERE ruta = 'Principal/consultarTipoMovimiento';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyTypeMove' WHERE ruta = 'Principal/modificarTipoMovimiento';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-deleteTypeMove' WHERE ruta = 'Principal/eliminarTipoMovimiento';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createProductGroup' WHERE ruta = 'Principal/crearProducto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultProductGroup' WHERE ruta = 'Principal/consultarProducto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyProductGroup' WHERE ruta = 'Principal/modificarProducto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-deleteProductGroup' WHERE ruta = 'Principal/eliminarProducto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createTypeInv' WHERE ruta = 'Principal/crearTipoInventario';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultTypeInv' WHERE ruta = 'Principal/consultarTipoInventario';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyTypeInv' WHERE ruta = 'Principal/modificarTipoInventario';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createTypeGroup' WHERE ruta = 'Principal/crearTipoGrupo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultTypeGroup' WHERE ruta = 'Principal/consultarTipoGrupo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyTypeGroup' WHERE ruta = 'Principal/modificarTipoGrupo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createItemAcc' WHERE ruta = 'Principal/crearItemAccesorios';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createItemBrand' WHERE ruta = 'Principal/crearMarca';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultItemBrand' WHERE ruta = 'Principal/consultarMarca';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyItemBrand' WHERE ruta = 'Principal/modificarMarca';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-deleteItemBrand' WHERE ruta = 'Principal/eliminarMarca';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createItemColor' WHERE ruta = 'Principal/crearColor';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultItemColor' WHERE ruta = 'Principal/consultarColor';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyItemColor' WHERE ruta = 'Principal/modificarColor';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-deleteItemColor' WHERE ruta = 'Principal/eliminarColor';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createItemState' WHERE ruta = 'Principal/crearEstadoItem';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultItemState' WHERE ruta = 'Principal/consultarEstadoItem';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyItemState' WHERE ruta = 'Principal/modificarEstadoItem';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createItemCat' WHERE ruta = 'Principal/crearCategoria';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultItemCat' WHERE ruta = 'Principal/consultarCategoria';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyItemCat' WHERE ruta = 'Principal/modificarCategoria';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createRefItem' WHERE ruta = 'Principal/crearReferencia';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultRefItem' WHERE ruta = 'Principal/consultarReferencia';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyRefItem' WHERE ruta = 'Principal/modificarReferencia';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-deleteRefItem' WHERE ruta = 'Principal/eliminarReferencia';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultCellar' WHERE ruta = 'Principal/consultarBodega';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createCellar' WHERE ruta = 'Principal/crearBodega';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyCellar' WHERE ruta = 'Principal/modificarBodega';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createConsLot' WHERE ruta = 'Principal/crearConsecutivoLote';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyConsLot' WHERE ruta = 'Principal/modificarConsecutivoLote';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createConsXSuc' WHERE ruta = 'Principal/crearConsecutivoSuc';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultConsXSuc' WHERE ruta = 'Principal/consultarConsecutivoSuc';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyConsXSuc' WHERE ruta = 'Principal/modificarConsecutivoSuc';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createSerialState' WHERE ruta = 'Principal/crearEstadoSerial';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultSerialState' WHERE ruta = 'Principal/consultarEstadoSerial';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifySerialState' WHERE ruta = 'Principal/modificarEstadoSerial';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-deleteSerialState' WHERE ruta = 'Principal/eliminarEstadoSerial';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createConcept' WHERE ruta = 'Principal/crearConcepto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultConcept' WHERE ruta = 'Principal/consultarConcepto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyConcept' WHERE ruta = 'Principal/modificarConcepto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createTypeConcept' WHERE ruta = 'Principal/crearTipoConcepto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultTypeConcept' WHERE ruta = 'Principal/consultarTipoConcepto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyTypeConcept' WHERE ruta = 'Principal/modificarTipoConcepto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createPricesList' WHERE ruta = 'Principal/crearListaPrecio';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyPricesList' WHERE ruta = 'Principal/modificarListaPrecio';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultPricesList' WHERE ruta = 'Principal/consultarListaPrecio';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createGroup' WHERE ruta = 'Principal/crearGrupo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultGroup' WHERE ruta = 'Principal/consultarGrupo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyGroup' WHERE ruta = 'Principal/modificarGrupo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-deleteGroup' WHERE ruta = 'Principal/eliminarGrupo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createItem' WHERE ruta = 'Principal/crearItem';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultItem' WHERE ruta = 'Principal/consultarItem';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyItem' WHERE ruta = 'Principal/modificarItem';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-compInvs' WHERE ruta = 'Consultas/compararInventario';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultInvGroups' WHERE ruta = 'Consultas/consultarInventarioGrupos';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultInvGrpUnserial' WHERE ruta = 'Consultas/consultarInventarioNSGrupos';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultInvDoc' WHERE ruta = 'Consultas/consultarInventarioDocumento';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultIvnAva' WHERE ruta = 'Consultas/consultarInventarioDisponible';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultInvNational' WHERE ruta = 'Consultas/consultarInventarioDisponibleNacional';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultInvPost30' WHERE ruta = 'Consultas/consultarEquiposVencidos';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultGenStock' WHERE ruta = 'Consultas/consultarStockGeneral';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consulTransfers' WHERE ruta = 'Consultas/consultarTraslados';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultSellsKinacu' WHERE ruta = 'Consultas/consultarVentasKinacu';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-changeSerialStates' WHERE ruta = 'Consultas/cambioEstadoSerial';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultResSerial' WHERE ruta = 'Consultas/consultarSerialAtrapado';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultSerial' WHERE ruta = 'Consultas/consultarSerial';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultSerialStates' WHERE ruta = 'Consultas/consultarEstadoSerial';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultLotSuc' WHERE ruta = 'Consultas/consultarLoteSurcursal';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultLot' WHERE ruta = 'Consultas/consultarLote';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultLotSerialsAv' WHERE ruta = 'Consultas/consultarLoteSerialesDisponibles';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultRefAccesory' WHERE ruta = 'Consultas/consultarReferenciaSinHomologo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-accesoryRelEquip' WHERE ruta = 'Accesorios/cargarFormulario/acceParaEquipo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultEquiPrice' WHERE ruta = 'Consultas/consultaPrecioAccesorios';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultEquipAccs' WHERE ruta = 'Consultas/consultarAccesoriosEquipo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultHomoEquip' WHERE ruta = 'Consultas/consultarHomologaEquipo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createHomo' WHERE ruta = 'Accesorios/cargarFormulario/newHomologo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultHomoRef' WHERE ruta = 'Accesorios/cargarFormulario/relHomologoRefer';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-relAccsHomo' WHERE ruta = 'Accesorios/cargarFormulario/relAcceHomologo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-relHomoAccs' WHERE ruta = 'Accesorios/formHomologoRelAccesorio';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultHomoItems' WHERE ruta = 'Consultas/consultarHomologaItem';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultAccsStock' WHERE ruta = 'Consultas/consultarStockAccesorios';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultItemInv' WHERE ruta = 'Consultas/consultarInventarioItem';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultGroupInv' WHERE ruta = 'Consultas/consultarInventarioGrupo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-returnBillClaro' WHERE ruta = 'portalSinges/inventario/documento021';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createDoc122' WHERE ruta = 'portalSinges/inventario/documento122';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultDoc122' WHERE ruta = 'portalSinges/inventario/consultarDocumento122';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createDoc121' WHERE ruta = 'portalSinges/inventario/documento121';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createBundle' WHERE ruta = 'bundles/nuevo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createConsPre' WHERE ruta = 'Precintos/crearConsecutivosPrecinto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultConsPre' WHERE ruta = 'Precintos/consultarConsecutivosPrecinto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-assignConsPre' WHERE ruta = ' Precintos/asignarConsecutivosPrecinto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultConsAssigned' WHERE ruta = ' Precintos/consultarConsecutivosAsignadosPrecinto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-editConsAssigned' WHERE ruta = ' Precintos/editarConsecutivosAsignadosPrecinto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createSeals' WHERE ruta = 'Precintos/crearPrecinto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultSeals' WHERE ruta = 'Precintos/verPrecintos';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifySeals' WHERE ruta = 'Precintos/modificarPrecinto';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc112' WHERE ruta = 'Principal/cargaDocumento/112';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc005' WHERE ruta = 'Principal/cargaDocumento/005';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc006' WHERE ruta = 'Principal/cargaDocumento/006';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc110' WHERE ruta = 'Principal/cargaDocumento/110';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc111' WHERE ruta = 'Principal/cargaDocumento/111';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc301' WHERE ruta = 'Principal/cargaDocumento/301';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc000' WHERE ruta = 'Principal/cargaDocumento/000';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc003' WHERE ruta = 'Principal/cargaDocumento/003';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc013' WHERE ruta = 'Principal/cargaDocumento/013';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc004' WHERE ruta = 'Principal/cargaDocumento/004';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc210' WHERE ruta = 'Principal/cargaDocumento/210';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc211' WHERE ruta = 'Principal/cargaDocumento/211';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc011' WHERE ruta = 'Principal/cargaDocumento/011';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc011-1' WHERE ruta = 'Principal/cargaDocumento/011/1';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc011-2-1' WHERE ruta = 'index.php/Principal/cargaDocumentoPrevio/011/2/1';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc007' WHERE ruta = 'Principal/cargaDocumento/007';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadDoc007-1' WHERE ruta = 'Principal/cargaDocumento/007/1';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-modifyPurchOrder' WHERE ruta = 'Principal/modificarOrdenCompra';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-consultPurchOrder' WHERE ruta = 'Principal/consultarOrdenCompra';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-createReport' WHERE ruta = 'Principal/crearReporte';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadFileCat' WHERE ruta = 'Principal/cargarArchivoGeneral/categoria';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadFileRef' WHERE ruta = 'Principal/cargarArchivoGeneral/referencia';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadFileItem' WHERE ruta = 'Principal/cargarArchivoGeneral/items';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadFileSerial' WHERE ruta = 'Principal/cargarArchivoSerial/serial';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadFileRelSuc' WHERE ruta = 'Principal/cargarArchivoAccesorios/relSuc';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadFileSucListPrices' WHERE ruta = 'Principal/cargarArchivoAccesorios/sucListaPre';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadFileHomoEquip' WHERE ruta = 'Principal/cargarArchivoAccesorios/homologaEquipo';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadListPrices' WHERE ruta = 'Principal/cargarArchivoAccesorios/listaPrecios';
UPDATE portal_menuAplicacion SET codPermiso = 'inv-loadListCodes' WHERE ruta = 'Principal/cargarArchivoAccesorios/listCodProd';