INSERT INTO portal_aplicacionCodigos VALUES ('clf-consultConReports', 'Consultar reportes contrato');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-consultConReports' WHERE ruta = 'adminClaroFijo/reportesContratos';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-createConContract', 'Crear consecutivo contrato');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-createConContract' WHERE ruta = 'adminClaroFijo/tplCrearConsecutivosContrato';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-editService', 'Editar servicio');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-editService' WHERE ruta = 'adminClaroFijo/editarServ/editar';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-editAditionalService', 'Editar servicio adicional');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-editAditionalService' WHERE ruta = 'adminClaroFijo/formEditaAdicional/editar';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-deleteAditionalServic', 'Eliminar servicio adicional');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-deleteAditionalServic' WHERE ruta = 'adminClaroFijo/formEditaAdicional/eliminar';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-consultPackaging', 'Consultar empaquetado');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-consultPackaging' WHERE ruta = 'adminClaroFijo/formConsultarEmpaquetado';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-editPackaging', 'Editar empaquetado');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-editPackaging' WHERE ruta = 'adminClaroFijo/formConsultarEmpaquetado/editar';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-deletePackaging', 'Eliminar empaquetado');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-deletePackaging' WHERE ruta = 'adminClaroFijo/formConsultarEmpaquetado/eliminar';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-createCity', 'Crear ciudad');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-createCity' WHERE ruta = 'adminClaroFijo/CreaCiudad';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-insertCity', 'Insertar ciudad');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-insertCity' WHERE ruta = 'adminClaroFijo/formCiudad/insertar';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-deleteCity', 'Eliminar ciudad');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-deleteCity' WHERE ruta = 'adminClaroFijo/formCiudad/eliminar';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-createCampaigns', 'Creación de campañas');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-createCampaigns' WHERE ruta = 'circulares/Circulares';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-modifyConsecutive', 'Modificar consecutivos sucursal');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-modifyConsecutive' WHERE ruta = 'adminClaroFijo/tplModificarConsecutivoSuc';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-consultContList', 'Consultar listado de contratos');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-consultContList' WHERE ruta = 'modificarEstado/listadoContratos';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-assignConXSuc', 'Asignar consecutivos por sucursal');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-assignConXSuc' WHERE ruta = 'adminClaroFijo/tplAsignarConsecutivo';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-consultCity', 'Consultar ciudad');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-consultCity' WHERE ruta = 'adminClaroFijo/formCiudad/consultar';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-consultConXSuc', 'Consultar consecutivos por sucursal');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-consultConXSuc' WHERE ruta = 'adminClaroFijo/tplConsultarConsecutivoSuc';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-serviceDesk', 'ServiceDesk claro fijo');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-serviceDesk' WHERE ruta = 'serviceDeskCf';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-registerOT', 'Registro de orden de trabajo');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-registerOT' WHERE ruta = 'dth_controller/orden_de_trabajo';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-updateContractCF', 'Actualizar orden de trabajo');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-updateContractCF' WHERE ruta = 'actualizarContratoCF';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-modifyState', 'Edición de contratos claro fijo');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-modifyState' WHERE ruta = 'modificarEstado/modificar_contrato';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-genReportContracts', 'Reporte general contratos claro fijo');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-genReportContracts' WHERE ruta = 'adminClaroFijo/reporteGeneralContratosCF';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-consultConContract', 'Consultar consecutivo contrato');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-consultConContract' WHERE ruta = 'adminClaroFijo/tplConsultarConsecutivosContrato';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-consultService', 'Consulta servicio');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-consultService' WHERE ruta = 'adminClaroFijo/editarServ/consulta';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-consultAdtServ', 'Consultar servicio adicional');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-consultAdtServ' WHERE ruta = 'adminClaroFijo/formEditaAdicional/consultar';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-insertAdtServ', 'Insertar servicio adicional');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-insertAdtServ' WHERE ruta = 'adminClaroFijo/formCreaAdicional';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-insertPackaging', 'Insertar empaquetado');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-insertPackaging' WHERE ruta = 'adminClaroFijo/formCreaEmpaquetado';
INSERT INTO portal_aplicacionCodigos VALUES ('clf-deleteService', 'Eliminar servicio');
UPDATE portal_menuAplicacion SET codPermiso = 'clf-deleteService' WHERE ruta = 'adminClaroFijo/editarServ/eliminar';